language: python
python:
  - "3.6"
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
script:
  - py.test --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls