language: python
python:
- '3.6'
install:
  - make install TARGET=test
script:
  - pip install python-coveralls
  - make doc
  - make coverage
after_success:
- coveralls
deploy:
  provider: pypi
  user: SwamyDev
  password:
    secure: Xv+8rvF1JMrl3SfKTacqWp0dAmAF47OF0ulphZUETkVffoZDgJ5hvSwEl9k+M+7C2OhTQR+RKFWYKdOa+oS726gBxrHu8ZTPprZ/ENwEyE6XMMTP0DqVOoXy/MeG+21pqktNnJ5aRMbHgFY9bdaTC3I608dpUozcNBDyf8SB3FoASeWUZtK0ikiHGQLCM7hF1cN5Jn9WRGtCEbtvFtoOSdCsUmShEr7QTWkH7mgwO8iAlsEwXsQbmg+l/uP8wNQoChjsDKAqL9JQ/Y58mg6GRUNeSHu1IGUXxzPUNVqTWF9jSTPn6pPF1lYeK4vymBZ8F2T1oo4EN6CV8thlvzYJwgcD3BU7eLWMhofKQ60pohivsVgq6N80DFDebU3XbDy4d2heSWmidwYVnOha0WyE1SZzLrfBtfmb+n2+ktSlMvKEJpRiv5gLuT4p1ShikLS2XG9Jx5Tdfaz/wXDAbNG3WHZu3g8iQEyBVCUCL3eJsD9qSasTjnhrVgANw9UX+TVD0DalVByi3TIP5jjOpH6cL5ayVRed2ot8HOK4gh1Zg/NMK7ycbWvskXJe3wiPQJFKpwzsrhwfcKKgqP4jK/W8HXb2VQdvBpjAxhcnY5UgEU6RM6OPm9HDVl7+K1jZrEkVT+aI6bE1r8Ocxl2+2CJsnRjD4V3xi60Rw8K7zBxkuA0=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
